Digitalcustomer/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('', include('accounts.urls')),
    path('user/', include("user.urls")),
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import *

app_name = "accounts"


urlpatterns = [
    path('', homepage, name='homepage'),
    path('signUp',signUpRedirect , name='signUp'),
    path('signIn',signInRedirect, name='signIn'),
    path('registerUser', registerUser, name='registerUser'),
    path('login', login, name='login'),

]

user/urls.py
from django.contrib import admin
from django.urls import path
from user.views import *
app_name = "user"



urlpatterns = [
    path('', userHomepage, name='homepage'),
    path('uploadDoc', uploadDocument, name='uploadDoc'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserDetails(models.Model):
    cnic = models.CharField(max_length=16)
    phoneNo = models.CharField(max_length=30)
    userId = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

user/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User,auth
from accounts.models import *
from django.http import HttpResponse, JsonResponse

# Create your views here.


def homepage(request):
    return render(request,'Home\index.html')


def signUpRedirect(request):
    return render(request,'Home\SignUp.html')


def signInRedirect(request):
    return render(request,'Home\SignIn.html')


def registerUser(request):
    if request.method=='POST':
        fName = request.POST["first_name"]
        lName = request.POST["last_name"]
        email = request.POST["email"]
        cnic = request.POST["cnic"]
        password = request.POST["password"]
        phoneNo = request.POST["phoneNumber"]
        print(fName)
        print(lName)
        print(email)
        print(cnic)
        print(password)
        print(phoneNo)
        if checkEmail(email):
            return JsonResponse({"status": False, "msg": "An account with entered email already exists."})
        user = User.objects.create_user(username=email, password=password, email=email,first_name=fName, last_name=lName)
        UserDetails.objects.create(cnic=cnic,phoneNo=phoneNo,userId_id=user.id)

        return redirect("user/")


def login(request):
    print('In Login request recieved ')
    if request.method == "POST":
        #   Finding if doctor or patient wants to log in
        username_post = request.POST['email']
        password_post = request.POST['password']
        print("email :", username_post)
        print("Password  :", password_post)
        user = auth.authenticate(username=username_post, password=password_post)
        print(user.id)
        # Finding if it is teacher or student that logged in
        if user is not None:
            try:
                print("Redirecting to user login")
                User.objects.get(id=user.id)
                auth.login(request, user)
                request.session["LoginType"] = "User"
                request.session.set_expiry(7200)  # 2 hours session expiry
                return redirect("user/")
            except:
                pass
    # If request is not validated or user is not valid, it is redirected to homepage
    request.session["LoginMessage"] = "Try Again"
    return redirect("/#section-login")




def checkEmail(email):
    try:
        if User.objects.filter(email=email).exists():
            return True
        return False
    except Exception as e:
        print("Exception in check_duplicate_email(accounts:helpers):", str(e))
        return False

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from accounts.models import *
from django.http import HttpResponse, JsonResponse
# Create your views here.


def userHomepage(request):
    return render(request,'Home\menu.html')


def uploadDocument(request):
    if request.user.is_authenticated:
        return render(request,'Home\\uplodeDocument.html')

templates/Home/SignIn.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
<title>Bootstrap Simple Registration Form</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
  *{
	margin: 0;
	padding: 0;
	font-family: Century Gothic;
}

header{
	height: 100vh;
	background-size: cover;
	background-position: center;
}

ul{
	float: right;
	list-style-type: none;
	margin-top: 25px;

}

ul li{
	display: inline-block;

}
ul li a{
	text-decoration: none;
	color: #fff;
	padding: 5px 20px;
	border: 1px solid transparent;
	transition: 0.6s ease;
}
ul li a:hover{
	background-color: #fff;
	color: #000;
}

ul li.active a{
	background-color: #fff;
	color: #000;
}
.logo img{

	float: left;
	width: 150px;
	height: auto;

}
.main{
	max-width: 1200px;
	margin: auto;
}
.title{
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%,-50%);
}
.title h1{
	color: #fff;
	font-size: 70px;

}
	body {
		color: #fff;
		background: #63738a;

	background-image:linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url("{% static '/images/image.jpeg'  %}");
	height: 100vh;
	background-size: cover;
	background-position: center;

		font-family: 'Roboto', sans-serif;
	}
    .form-control{
		height: 40px;
		box-shadow: none;
		color: #969fa4;
	}
	.form-control:focus{
		border-color: #5cb85c;
	}
    .form-control, .btn{
        border-radius: 3px;
    }
	.signin-form{
		width: 400px;
		margin: 0 auto;
		padding: 30px 0;
	}
	.signin-form h2{
		color: #636363;
        margin: 0 0 15px;
		position: relative;
		text-align: center;
    }
	.signin-form h2:before, .signup-form h2:after{
		content: "";
		height: 2px;
		width: 30%;
		background: #d4d4d4;
		position: absolute;
		top: 50%;
		z-index: 2;
	}
	.signin-form h2:before{
		left: 0;
	}
	.signin-form h2:after{
		right: 0;
	}
    .signin-form .hint-text{
		color: #999;
		margin-bottom: 30px;
		text-align: center;
	}
    .signin-form form{
		color: #999;
		border-radius: 3px;
    	margin-bottom: 15px;
        background: #f2f3f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
	.signin-form .form-group{
		margin-bottom: 20px;
	}
	.signin-form input[type="checkbox"]{
		margin-top: 3px;
	}
	.signin-form .btn{
        font-size: 16px;
        font-weight: bold;
		min-width: 140px;
        outline: none !important;
    }
	.signin-form .row div:first-child{
		padding-right: 10px;
	}
	.signin-form .row div:last-child{
		padding-left: 10px;
	}
    .signin-form a{
		color: #fff;
		text-decoration: underline;
	}
    .signin-form a:hover{
		text-decoration: none;
	}
	.signin-form form a{
		color: #5cb85c;
		text-decoration: none;
	}
	.signin-form form a:hover{
		text-decoration: underline;
	}
</style>
</head>
<body>
<header>

<div class="main">
			<div class="logo">
				<img src="{% static 'images\logo.jpg' %}" >
			<ul>
				<li><a href="{% url 'accounts:homepage' %}">Home</a></li>
				<li><a href="{% url 'accounts:signUp' %}">Signup</a></li>
				<li class="active"><a href="{% url 'accounts:signIn' %}">Login</a></li>
				<li><a href="#">About Us</a></li>
			</ul>
			</div>

</div>


<div class="signin-form">
    <form action="{% url 'accounts:login' %}" method="post">
		{% csrf_token %}
        <h2>Sign in</h2>
		<p class="hint-text">Sign in to your account</p>
        <div class="form-group">
        	<input type="email" class="form-control" name="email" placeholder="Email" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>

		<div class="form-group">
            <button type="submit" class="btn btn-success btn-lg btn-block">Sign in</button>
        </div>
    </form>
	<div class="text-center">Not a user? <a href="{% url 'accounts:signUp' %}">Sign up</a></div>
</div>
    </header>
</body>
</html>
</body>
</html>

templates/Home/SignUp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
<title>Simple Registration Form</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
    .logo img{

	float: left;
	width: 150px;
	height: auto;

}
    header{
	background-image:linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url("{% static '/images/image.jpeg'  %}");
	height: 100vh;
	background-size: cover;
	background-position: center;
}
    ul{
	float: right;
	list-style-type: none;
	margin-top: 25px;

}

ul li{
	display: inline-block;

}
ul li a{
	text-decoration: none;
	color: #fff;
	padding: 5px 20px;
	border: 1px solid transparent;
	transition: 0.6s ease;
}
ul li a:hover{
	background-color: #fff;
	color: #000;
}

ul li.active a{
	background-color: #fff;
	color: #000;
}
.main{
	max-width: 1200px;
	margin: auto;
}
	body {
		color: #fff;
		background: #63738a;

	background-image:linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url("{% static '/images/image.jpeg'  %}");
	height: 100vh;
	background-size: cover;
	background-position: center;

		font-family: 'Roboto', sans-serif;
	}

    .form-control{
		height: 33px;
		box-shadow: none;
		color: #969fa4;
	}
	.form-control:focus{
		border-color: #5cb85c;
	}
    .form-control, .btn{
        border-radius: 3px;
    }
	.signup-form{
		width: 400px;
		margin: 0 auto;
		padding: 30px 0;
	}
	.signup-form h2{
		color: #636363;
        margin: 0 0 15px;
		position: relative;
		text-align: center;
    }
	.signup-form h2:before, .signup-form h2:after{
		content: "";
		height: 2px;
		width: 30%;
		background: #d4d4d4;
		position: absolute;
		top: 50%;
		z-index: 2;
	}
	.signup-form h2:before{
		left: 0;
	}
	.signup-form h2:after{
		right: 0;
	}
    .signup-form .hint-text{
		color: #999;
		margin-bottom: 30px;
		text-align: center;
	}
    .signup-form form{
		color: #999;
		border-radius: 3px;
    	margin-bottom: 15px;
        background: #f2f3f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
	.signup-form .form-group{
		margin-bottom: 20px;
	}
	.signup-form input[type="checkbox"]{
		margin-top: 3px;
	}
	.signup-form .btn{
        font-size: 16px;
        font-weight: bold;
		min-width: 140px;
        outline: none !important;
    }
	.signup-form .row div:first-child{
		padding-right: 10px;
	}
	.signup-form .row div:last-child{
		padding-left: 10px;
	}
    .signup-form a{
		color: #fff;
		text-decoration: underline;
	}
    .signup-form a:hover{
		text-decoration: none;
	}
	.signup-form form a{
		color: #5cb85c;
		text-decoration: none;
	}
	.signup-form form a:hover{
		text-decoration: underline;
	}
</style>

<body>


<header>
		<div class="main">
			<div class="logo">
				<img src="{% static 'images\logo.jpg' %}" >
			<ul>
				<li><a href="{% url 'accounts:homepage' %}">Home</a></li>
				<li class="active"><a href="{% url 'accounts:signUp' %}">Signup</a></li>
				<li><a href="{% url 'accounts:signIn' %}">Login</a></li>
				<li><a href="#">About Us</a></li>
			</ul>
			</div>


            <div class="signup-form">
    <form  action="{% url 'accounts:registerUser' %}" id="register" method="Post" >
        {% csrf_token %}
        <h2>Register</h2>
		<p class="hint-text">Create your account. It's free and only takes a minute.</p>
        <div class="form-group">
			<div class="row">
				<div class="col-xs-6"><input type="text" class="form-control" name="first_name" placeholder="First Name" required="required"></div>
				<div class="col-xs-6"><input type="text" class="form-control" name="last_name" placeholder="Last Name" required="required"></div>
			</div>
        </div>
        <div class="form-group">
        	<input type="email" class="form-control" name="email" placeholder="Email" required="required">
        </div>
         <div class="form-group">
        	<input type="tel" class="form-control" pattern="[0-9]{5}-[0-9]{7}-[0-9]{1}" name="cnic" placeholder="CNIC" required="required">
        </div>
        <div class="form-group">
        	<input type="tel" class="form-control"  name="phoneNumber" placeholder="Phone Number" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password" required="required">
        </div>
		<div class="form-group">
            <button type="submit" class="btn btn-success btn-lg btn-block">Register Now</button>
        </div>
    </form>
	<div class="text-center">Already have an account? <a href="{% url 'accounts:signIn'%}">Sign in</a></div>
</div>
</header>

<body>

</body>
</html>
</body>

<script>

    function matchPasssword() {

    }

    function register() {

    }


</script>
</html>

templates/Home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


   <style>
    *{
	margin: 0;
	padding: 0;
	font-family: Century Gothic;
}

header{
	background-image:linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url("{% static '/images/image.jpeg'  %}");
	height: 100vh;
	background-size: cover;
	background-position: center;
}

ul{
	float: right;
	list-style-type: none;
	margin-top: 25px;

}

ul li{
	display: inline-block;

}
ul li a{
	text-decoration: none;
	color: #fff;
	padding: 5px 20px;
	border: 1px solid transparent;
	transition: 0.6s ease;
}
ul li a:hover{
	background-color: #fff;
	color: #000;
}

ul li.active a{
	background-color: #fff;
	color: #000;
}
.logo img{

	float: left;
	width: 150px;
	height: auto;

}
.main{
	max-width: 1200px;
	margin: auto;
}
.title{
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%,-50%);
}
.title h1{
	color: #fff;
	font-size: 70px;

}
   </style>


<head>
    <meta charset="UTF-8">

    <title>HOME PAGE</title>
</head>
<body>
<header>
		<div class="main">
			<div class="logo">
				<img src="{% static 'images\logo.jpg' %}" >
			<ul>
				<li class="active"><a href="{% url 'accounts:homepage' %}">Home</a></li>
				<li><a href="{% url 'accounts:signUp' %}">Signup</a></li>
				<li><a href="{% url 'accounts:signIn' %}">Login</a></li>
				<li><a href="#">About Us</a></li>
			</ul>
			</div>
			<div class="title">
				<h1>Digital Customer Onboarding</h1>
			</div>
</header>

</body>
</html>

templates/Home/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
    *{
	margin: 0;
	padding: 0;
	font-family: Century Gothic;
}

header{
	background-image:linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url("{% static '/images/image.jpeg'  %}");
	height: 100vh;
	background-size: cover;
	background-position: center;
}

ul{
	float: right;
	list-style-type: none;
	margin-top: 25px;

}

ul li{
	display: inline-block;

}
ul li a{
	text-decoration: none;
	color: #fff;
	padding: 5px 20px;
	border: 1px solid transparent;
	transition: 0.6s ease;
}
ul li a:hover{
	background-color: #fff;
	color: #000;
}

ul li.active a{
	background-color: #fff;
	color: #000;
}
.logo img{

	float: left;
	width: 150px;
	height: auto;

}
.main{
	max-width: 1200px;
	margin: auto;
}
.title{
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%,-50%);
}
.title h1{
	color: #fff;
	font-size: 60px;

}
    <title>Title</title>
    </style>
    <title>HOME PAGE</title>
</head>
<body>
<header>
		<div class="main">
			<div class="logo">
				<img src=" {% static 'images\logo.jpg' %}" >
			<ul>
				<li class="active"><a href="#">Home</a></li>
				<li><a href="#">Upload Picture</a></li>
				<li><a href="{% url 'user:uploadDoc' %}">Upload Documents</a></li>

			</ul>
			</div>
			<div class="title">
				<h1>Welcome To Digital Customer Onboarding</h1>
			</div>
</header>

</body>
</html>

templates/Home/uplodeDocument.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Title</title>
    <style>
        * {
  box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
}

body {
  font-family: 'Montserrat', sans-serif;
  background-image:linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url("{% static '/images/image.jpeg'  %}");
}

.wrapper {
  margin: auto;
  max-width: 640px;
  padding-top: 60px;
  text-align: center;
}

.container {
  background-color: #f9f9f9;
  padding: 20px;
  border-radius: 10px;
  /*border: 0.5px solid rgba(130, 130, 130, 0.25);*/
  /*box-shadow: 0 2px 3px rgba(0, 0, 0, 0.1),
              0 0 0 1px rgba(0, 0, 0, 0.1);*/
}

h1 {
  color: #130f40;
  font-family: 'Varela Round', sans-serif;
  letter-spacing: -.5px;
  font-weight: 700;
  padding-bottom: 10px;
}

.upload-container {
  background-color: rgb(239, 239, 239);
  border-radius: 6px;
  padding: 10px;
}

.border-container {
  border: 5px dashed rgba(198, 198, 198, 0.65);
  border-radius: 6px;
  padding: 20px;
}

.border-container p {
  color: #130f40;
  font-weight: 600;
  font-size: 1.1em;
  letter-spacing: -1px;
  margin-top: 30px;
  margin-bottom: 0;
  opacity: 0.65;
}

#file-browser {
  text-decoration: none;
  color: rgb(22,42,255);
  border-bottom: 3px dotted rgba(22, 22, 255, 0.85);
}

#file-browser:hover {
  color: rgb(0, 0, 255);
  border-bottom: 3px dotted rgba(0, 0, 255, 0.85);
}

.icons {
  color: #95afc0;
  opacity: 0.55;
}
    </style>
</head>
<body>

<div class="wrapper">
  <div class="container">
    <h1>Upload a file</h1>
    <div class="upload-container">
      <div class="border-container">
        <div class="icons fa-4x">
          <i class="fas fa-file-image" data-fa-transform="shrink-3 down-2 left-6 rotate--45"></i>
          <i class="fas fa-file-alt" data-fa-transform="shrink-2 up-4"></i>
          <i class="fas fa-file-pdf" data-fa-transform="shrink-3 down-2 right-6 rotate-45"></i>
        </div>
        <!--<input type="file" id="file-upload">-->
        <p>Drag and drop files here, or
          <a href="#" id="file-browser">browse</a> your computer.</p>
      </div>
    </div>
  </div>
</div>




</body>
</html>